// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARCHYjQaLOy6vUvD0HOVPpa5VaPRKKOOQ',
    appId: '1:376428792461:web:3a21588eed0e387f9cf0c4',
    messagingSenderId: '376428792461',
    projectId: 'um-connect',
    authDomain: 'um-connect.firebaseapp.com',
    storageBucket: 'um-connect.firebasestorage.app',
    measurementId: 'G-E7SDRXZRT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzlx6582uenVkHWzWmUly4z2C0rigGrEg',
    appId: '1:376428792461:android:abf62679ba3440059cf0c4',
    messagingSenderId: '376428792461',
    projectId: 'um-connect',
    storageBucket: 'um-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrNGi_sSC9nV4nMaJTvgzLDqh_Jd62AVk',
    appId: '1:376428792461:ios:0d65d09b4942a42a9cf0c4',
    messagingSenderId: '376428792461',
    projectId: 'um-connect',
    storageBucket: 'um-connect.firebasestorage.app',
    iosBundleId: 'com.example.umConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrNGi_sSC9nV4nMaJTvgzLDqh_Jd62AVk',
    appId: '1:376428792461:ios:0d65d09b4942a42a9cf0c4',
    messagingSenderId: '376428792461',
    projectId: 'um-connect',
    storageBucket: 'um-connect.firebasestorage.app',
    iosBundleId: 'com.example.umConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARCHYjQaLOy6vUvD0HOVPpa5VaPRKKOOQ',
    appId: '1:376428792461:web:b92c98cfa8d60e0a9cf0c4',
    messagingSenderId: '376428792461',
    projectId: 'um-connect',
    authDomain: 'um-connect.firebaseapp.com',
    storageBucket: 'um-connect.firebasestorage.app',
    measurementId: 'G-NEL3V1HXCX',
  );
}
